#!/usr/bin/env python3
"""
V8.5 bootstrap_hermes_homes.py

For each active agent, create a Hermes home directory at
~/.hermes-<slug>/ with:
  - config.yaml         model + provider + toolsets seeded
  - SOUL.md             agent's role + personality (from AGENTS.md body)
  - MEMORY.md           seed with role + reportsTo + workflow position
  - USER.md             main contact (from manifest.main_contact)
  - skills/seed.md      copy of agent's seed skill

Owen is skipped (null model). Idempotent: re-running updates files in place;
existing memory/skill content is NOT clobbered (only seed files written).

Usage:
  python3 bootstrap_hermes_homes.py [--dry-run] [--only SLUG[,SLUG,...]] [--force-soul]

Flags:
  --dry-run     Print what would be written, no filesystem changes.
  --only        Only process the comma-separated slugs.
  --force-soul  Overwrite SOUL.md even if it exists (default: preserve).
"""
import argparse
import json
import os
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SH = ROOT / "Pantheon"
PKG = ROOT / "pantheon"
MANIFEST = ROOT / "manifest.json"

SKIPPED_SLUGS = {"owen"}  # see PATCH_NOTES_V8_5.md

# Mirror of converter HERMES_PROVIDER_MAP — keep in sync.
HERMES_PROVIDER_MAP = {
    "anthropic/":  "auto",
    "openai/":     "openai-codex",
    "google/":     "openrouter",
    "deepseek/":   "openrouter",
    "moonshotai/": "kimi-coding",
}


def slugify(s):
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


def resolve_provider(model):
    if not model:
        return None
    for prefix, provider in HERMES_PROVIDER_MAP.items():
        if model.startswith(prefix):
            return provider
    return None


def read_short_slugs():
    """Read SHORT_SLUG map from convert_to_agentcompanies_v1.py without
    importing it (avoids running the whole script). The map is a literal
    dict at the top of that file.
    """
    src = (ROOT / "scripts" / "convert_to_agentcompanies_v1.py").read_text(encoding="utf-8")
    m = re.search(r"SHORT_SLUG\s*=\s*\{(.+?)\}", src, re.DOTALL)
    if not m:
        return None
    block = "{" + m.group(1) + "}"
    # ast.literal_eval is the safe parser.
    import ast
    try:
        return ast.literal_eval(block)
    except Exception as e:
        print(f"WARN: failed to parse SHORT_SLUG: {e}", file=sys.stderr)
        return None


def extract_agents_md_body(agent_dir):
    """Read AGENTS.md and return everything after the frontmatter."""
    f = agent_dir / "AGENTS.md"
    if not f.exists():
        return None
    text = f.read_text(encoding="utf-8")
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            return parts[2].lstrip("\n")
    return text


def write_config_yaml(home, agent):
    """Drop a non-interactive Hermes config.yaml. Skips the setup wizard."""
    model = agent["model"]
    provider = resolve_provider(model)
    lines = [
        "# Generated by bootstrap_hermes_homes.py (V8.5)",
        f"# Agent: {agent['slug']}  ({agent.get('name', '')})",
        "",
        "model:",
        f"  provider: {provider}",
        f"  name: {model}",
        "",
        "toolsets:",
        "  enabled:",
        "    - terminal",
        "    - file",
        "    - web",
        "    - browser",
        "    - code_execution",
        "    - mcp",
        "",
        "ui:",
        "  banner: false",
        "  spinner: false",
        "",
        "memory:",
        "  enabled: true",
        "",
        "skills:",
        "  local_dir: skills",
        "",
    ]
    if agent.get("effort"):
        lines += [
            "extras:",
            "  # Effort hint — Hermes will pass --effort to providers that support it",
            f"  effort: {agent['effort']}",
            "",
        ]
    (home / "config.yaml").write_text("\n".join(lines), encoding="utf-8")


def write_memory_md(home, agent):
    """Seed memory file — Hermes will append to this across heartbeats."""
    f = home / "MEMORY.md"
    if f.exists():
        return  # preserve real memory
    lines = [
        "# MEMORY",
        "",
        f"Agent slug: {agent['slug']}",
        f"Canonical id: {agent.get('canonical_id') or agent['slug']}",
        f"Role: {agent.get('role') or '(unspecified)'}",
        f"Reports to: {agent.get('reports_to') or 'none'}",
        f"Model: {agent['model']}",
        "",
        "## Workflow position",
        "",
        agent.get("workflow_position") or "(populated by Paperclip on first dispatch)",
        "",
        "## Notes",
        "",
        "Seeded by V8.5 bootstrap. Hermes will grow this file as the agent works.",
        "",
    ]
    f.write_text("\n".join(lines), encoding="utf-8")


def write_user_md(home, main_contact):
    """User profile — main contact / boss for this agent.
    manifest.main_contact may be a string OR a dict (name/role/harness/model).
    """
    f = home / "USER.md"
    if f.exists():
        return
    if isinstance(main_contact, dict):
        name = main_contact.get("name", "Arthur")
        role = main_contact.get("role", "Project Manager")
        harness = main_contact.get("harness", "Hermes")
        model = main_contact.get("model", "")
        contact_line = f"{name} — {role}" + (f" (harness: {harness}, model: {model})" if model else "")
    else:
        contact_line = str(main_contact)
    lines = [
        "# USER",
        "",
        f"Main contact: {contact_line}",
        "",
        "The user is the human operator overseeing the Pantheon. "
        "Arthur (Project Manager) is the in-company manager; the human contact is the ultimate "
        "approver for governance, merges, deploys, and trading rule changes.",
        "",
    ]
    f.write_text("\n".join(lines), encoding="utf-8")


def write_soul_md(home, agent_dir, force=False):
    f = home / "SOUL.md"
    if f.exists() and not force:
        return
    body = extract_agents_md_body(agent_dir) or ""
    lines = [
        "# SOUL",
        "",
        "## Identity",
        "",
        body.strip(),
        "",
    ]
    f.write_text("\n".join(lines), encoding="utf-8")


def copy_seed_skill(home, agent_dir):
    """Copy agent's SKILL.md into the home's local skill dir.
    Converter emits skills/<slug>-seed/SKILL.md (suffix is part of the slug
    used in agentcompanies/v1 to disambiguate skill ids from agent ids).
    """
    skills_dir = home / "skills"
    skills_dir.mkdir(exist_ok=True)
    pkg_skill = PKG / "skills" / f"{agent_dir.name}-seed" / "SKILL.md"
    if pkg_skill.exists():
        shutil.copyfile(pkg_skill, skills_dir / "seed.md")
    else:
        print(f"  WARN: no seed skill found for {agent_dir.name} at {pkg_skill}", file=sys.stderr)


def load_agents():
    """Load agents from the canonical source (organization.import.json) and
    join with .paperclip.yaml-derived slug info.
    """
    org = json.loads((SH / "paperclip" / "organization.import.json").read_text(encoding="utf-8"))
    short = read_short_slugs() or {}
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    canonical = manifest.get("canonical_agent_ids", {})
    inv_canonical = {v: k for k, v in canonical.items()}

    out = []
    for a in org.get("agents", []):
        aid = a.get("id")
        slug = short.get(aid) or inv_canonical.get(aid) or slugify(a.get("name", aid))
        if not slug:
            continue
        out.append({
            "id": aid,
            "slug": slug,
            "canonical_id": aid,
            "name": a.get("name"),
            "model": a.get("model"),
            "effort": a.get("effort"),
            "role": a.get("role"),
            "reports_to": a.get("reportsTo") or a.get("reports_to"),
            "workflow_position": a.get("workflow_position"),
        })
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--only", default="", help="Comma-separated slugs to process")
    ap.add_argument("--force-soul", action="store_true")
    args = ap.parse_args()

    if not PKG.exists():
        print(f"ERROR: {PKG} not found — run convert_to_agentcompanies_v1.py first.", file=sys.stderr)
        sys.exit(1)

    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    main_contact = manifest.get("main_contact", "Arthur — Project Manager")

    only = {s.strip() for s in args.only.split(",") if s.strip()}
    home_root = Path(os.path.expanduser("~"))

    agents = load_agents()
    n_active = 0
    n_skipped = 0
    n_missing_provider = 0

    for agent in agents:
        slug = agent["slug"]
        if only and slug not in only:
            continue
        if slug in SKIPPED_SLUGS or agent["model"] is None:
            print(f"SKIP {slug:<10} (no model / explicit skip)")
            n_skipped += 1
            continue
        if resolve_provider(agent["model"]) is None:
            print(f"SKIP {slug:<10} model={agent['model']!r} — no provider mapping")
            n_missing_provider += 1
            continue

        home = home_root / f".hermes-{slug}"
        if args.dry_run:
            print(f"DRY  {slug:<10} -> {home}")
            n_active += 1
            continue

        home.mkdir(parents=True, exist_ok=True)
        agent_dir = PKG / "agents" / slug
        write_config_yaml(home, agent)
        write_memory_md(home, agent)
        write_user_md(home, main_contact)
        write_soul_md(home, agent_dir, force=args.force_soul)
        copy_seed_skill(home, agent_dir)
        print(f"OK   {slug:<10} -> {home}")
        n_active += 1

    print(f"\nSummary: {n_active} active, {n_skipped} skipped, {n_missing_provider} no-provider.")
    if n_missing_provider:
        sys.exit(2)


if __name__ == "__main__":
    main()
