#!/usr/bin/env python3
"""
V8.5: validate that the generated software-house/ package routes every active
agent through the hermes_local adapter with a per-agent HERMES_HOME.

Checks (against software-house/.paperclip.yaml):
  1. Every agent block (except Owen) has adapter.type == hermes_local.
  2. adapter.config.model is non-empty (provider/model format).
  3. adapter.config.provider is non-empty and in the known set.
  4. adapter.config.env.HERMES_HOME == ~/.hermes-<slug>  (slug must match).
  5. Owen has no adapter block (intentional skip, see manifest.json).
  6. Every canonical agent in manifest.canonical_agent_ids has a corresponding
     directory under software-house/agents/.

Exit code 0 = green; 1 = at least one failure.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PKG = ROOT / "software-house"
YAML = PKG / ".paperclip.yaml"
MANIFEST = ROOT / "manifest.json"

VALID_PROVIDERS = {
    "auto", "openrouter", "nous", "openai-codex", "zai",
    "kimi-coding", "minimax", "minimax-cn",
}

SKIPPED_SLUGS = {"owen"}  # see PATCH_NOTES_V8_5.md


def fail(msg, failures):
    failures.append(msg)


def parse_yaml_agents(text):
    """Minimal YAML parser for the structure emitted by
    convert_to_agentcompanies_v1.write_paperclip_yaml(). Avoids a PyYAML
    dependency — the file is generated by us and has a known shape.

    Returns: { slug: { 'adapter_type': str|None,
                       'model': str|None,
                       'provider': str|None,
                       'hermes_home': str|None,
                       'has_adapter': bool } }
    """
    agents = {}
    current = None
    cur = None
    in_adapter = False
    in_config = False
    in_env = False
    in_agents_section = False

    for raw in text.splitlines():
        line = raw.rstrip()
        if not line:
            continue
        if line == "agents:":
            in_agents_section = True
            continue
        if not in_agents_section:
            continue
        # End of agents section: any top-level key that is not indented.
        if re.match(r"^[a-z_]+:\s*$", line) and not line.startswith(" "):
            in_agents_section = False
            continue

        m = re.match(r"^  ([a-z_-]+):\s*$", line)
        if m:
            current = m.group(1)
            cur = {"adapter_type": None, "model": None, "provider": None,
                   "hermes_home": None, "has_adapter": False}
            agents[current] = cur
            in_adapter = in_config = in_env = False
            continue

        if cur is None:
            continue

        if re.match(r"^    adapter:\s*$", line):
            in_adapter = True
            in_config = in_env = False
            cur["has_adapter"] = True
            continue
        if in_adapter and re.match(r"^      type:\s*(.+)$", line):
            cur["adapter_type"] = re.match(r"^      type:\s*(.+)$", line).group(1).strip()
            continue
        if in_adapter and re.match(r"^      config:\s*$", line):
            in_config = True
            continue
        if in_config and re.match(r"^        model:\s*(.+)$", line):
            cur["model"] = re.match(r"^        model:\s*(.+)$", line).group(1).strip()
            continue
        if in_config and re.match(r"^        provider:\s*(.+)$", line):
            cur["provider"] = re.match(r"^        provider:\s*(.+)$", line).group(1).strip()
            continue
        if in_config and re.match(r"^        env:\s*$", line):
            in_env = True
            continue
        if in_env and re.match(r"^          HERMES_HOME:\s*(.+)$", line):
            cur["hermes_home"] = re.match(r"^          HERMES_HOME:\s*(.+)$", line).group(1).strip()
            continue

    return agents


def main():
    failures = []

    if not PKG.exists():
        print("SKIP: software-house/ not generated yet (run convert_to_agentcompanies_v1.py first).")
        sys.exit(0)

    if not YAML.exists():
        fail(f"{YAML} missing", failures)
        print("FAIL:", failures[0]); sys.exit(1)

    agents = parse_yaml_agents(YAML.read_text(encoding="utf-8"))
    if not agents:
        fail("No agent blocks parsed from .paperclip.yaml — converter may have failed silently.", failures)
        for m in failures: print("FAIL:", m)
        sys.exit(1)

    for slug, a in agents.items():
        if slug in SKIPPED_SLUGS:
            if a["has_adapter"]:
                fail(f"{slug} should NOT have an adapter block (intentionally skipped) — found {a['adapter_type']}", failures)
            continue

        if not a["has_adapter"]:
            fail(f"{slug} has no adapter block — every active agent must use hermes_local", failures)
            continue

        if a["adapter_type"] != "hermes_local":
            fail(f"{slug} adapter.type = {a['adapter_type']!r} — expected hermes_local", failures)

        if not a["model"]:
            fail(f"{slug} adapter.config.model is empty", failures)
        elif "/" not in a["model"]:
            fail(f"{slug} adapter.config.model = {a['model']!r} — expected provider/model format", failures)

        if not a["provider"]:
            fail(f"{slug} adapter.config.provider is empty", failures)
        elif a["provider"] not in VALID_PROVIDERS:
            fail(f"{slug} adapter.config.provider = {a['provider']!r} — not in {sorted(VALID_PROVIDERS)}", failures)

        expected_home = f"~/.hermes-{slug}"
        if a["hermes_home"] != expected_home:
            fail(f"{slug} HERMES_HOME = {a['hermes_home']!r} — expected {expected_home!r}", failures)

    # Cross-check against manifest.canonical_agent_ids — every canonical slug
    # must have an agent directory.
    if MANIFEST.exists():
        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
        agents_dir = PKG / "agents"
        for slug in manifest.get("canonical_agent_ids", {}).keys():
            if not (agents_dir / slug).exists():
                fail(f"canonical slug {slug!r} has no directory under {agents_dir}", failures)

    if failures:
        print(f"FAIL ({len(failures)} issues):")
        for m in failures:
            print("  -", m)
        sys.exit(1)

    active = sum(1 for s, a in agents.items() if s not in SKIPPED_SLUGS and a["has_adapter"])
    skipped = sum(1 for s in agents if s in SKIPPED_SLUGS)
    print(f"OK: {active} agents routed through hermes_local; {skipped} intentionally skipped.")
    sys.exit(0)


if __name__ == "__main__":
    main()
